plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

def targetJavaFile = "src/main/java/evertech1/pingcounter/PingCounter.java"
def downloadURL = "https://modrinth.com/mod/ping-counter"

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

tasks.register("deleteLibsFile"){
	def file = file("$projectDir/build/libs/$archivesBaseName-$version"+".jar")
	file.delete();
}

tasks.register("copyFiles", Copy) {
	from "$projectDir/build/libs/$archivesBaseName-$version" + ".jar"
	into "$projectDir/build/jars/modrinth/"
	finalizedBy deleteLibsFile
}

tasks.register("restoreFiles"){
	doLast {
		def file = file(targetJavaFile)
		file.text = file.text.replace(downloadURL, "PLACEHOLDER_DOWNLOAD")
	}
}

tasks.register("modifyConstants"){
	doLast{
		def file = file(targetJavaFile)
		file.text = file.text.replace("PLACEHOLDER_DOWNLOAD", downloadURL)
	}
}

tasks.named('build'){
	finalizedBy copyFiles
}

tasks.named('compileJava'){
	dependsOn modifyConstants
	finalizedBy restoreFiles
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
	}
}