plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.103'
    id 'idea'
}
def targetJavaFile = "src/main/templates/META-INF/neoforge.mods.toml"
def updateURL_modrinth = "https://gist.githubusercontent.com/EverTech1/2a2b99b663a910156457a59ecec0375e/raw/updateModrinth.json"
def downloadURL_modrinth = "https://modrinth.com/mod/ping-counter"


tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
configurations {
    runtimeClasspath.extendsFrom localRuntime
}



var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}


tasks.register("deleteLibsFile", Delete){
    def file = file("$projectDir/build/libs/$archivesBaseName-$version"+".jar")
    file.delete();
}
tasks.register("copyFiles", Copy){
    from "$projectDir/build/libs/$archivesBaseName-$version"+".jar"
    into "$projectDir/build/jars/modrinth/"
    finalizedBy deleteLibsFile
}
tasks.register("restoreFiles"){
    doLast {
        def file = file(targetJavaFile)
        file.text = file.text.replace(updateURL_modrinth, "PLACEHOLDER_JSON")
        file.text = file.text.replace(downloadURL_modrinth, "PLACEHOLDER_DOWNLOAD")
    }
}

tasks.register("modifyConstants"){
    doLast{
        def file = file(targetJavaFile)
        file.text = file.text.replace("PLACEHOLDER_JSON", updateURL_modrinth)
        file.text = file.text.replace("PLACEHOLDER_DOWNLOAD", downloadURL_modrinth)
    }
}
tasks.named('build'){
    finalizedBy copyFiles
}
tasks.named('compileJava'){
    dependsOn modifyConstants
    finalizedBy restoreFiles
}
